In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2023-04-26 23:40:53.696246: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


TensorFlow version: 2.12.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
# 정수에서 부동 소수점 숫자로 변환
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 1s 0us/step


In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.07824149, 0.10107108, 0.10217129, 0.08438163, 0.10935652,
        0.10476505, 0.08124657, 0.05750736, 0.09370312, 0.18755588]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.09779438, 0.10005266, 0.1001628 , 0.0983967 , 0.10088509,
        0.10042294, 0.0980887 , 0.09578758, 0.09931819, 0.1090909 ]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.2983646

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


/usr/local/Caskroom/miniforge/base/envs/mlops/lib/python3.11/site-packages/keras/backend.py:5612: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 [==============================] - 4s 2ms/step - loss: 0.2970 - accuracy: 0.9133
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1452 - accuracy: 0.9572
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1091 - accuracy: 0.9673
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0873 - accuracy: 0.9736
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0751 - accuracy: 0.9764


In [13]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0687 - accuracy: 0.9800 - 255ms/epoch - 816us/step


[0.06866061687469482, 0.9800000190734863]

모델이 확률을 반환하도록 하려면 다음과 같이 훈련된 모델을 래핑하고 여기에 소프트맥스를 첨부할 수 있습니다.

In [14]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533715, 0.08533715, 0.08533715, 0.08533987, 0.08533715,
        0.08533716, 0.08533715, 0.23196274, 0.08533716, 0.08533726],
       [0.08533674, 0.08533675, 0.23196927, 0.08533675, 0.08533674,
        0.08533674, 0.08533674, 0.08533674, 0.08533674, 0.08533674],
       [0.08533945, 0.2319265 , 0.08534025, 0.08533948, 0.08533958,
        0.08533946, 0.08533996, 0.08534971, 0.08534618, 0.08533945],
       [0.23196799, 0.08533682, 0.08533714, 0.08533682, 0.08533682,
        0.08533683, 0.08533704, 0.08533685, 0.08533682, 0.08533683],
       [0.08537043, 0.08537041, 0.08537042, 0.08537041, 0.23143572,
        0.08537045, 0.08537048, 0.08537234, 0.08537043, 0.08559887]],
      dtype=float32)>